### PR TITLE
new tests and credential configuration added

### PR DESCRIPTION
**Pull request by joedinsmoor**

### CODE REVIEW

**Comment by joedinsmoor** [comment]
where am I going wrong here? My VM is running this correctly, but the test seems to think otherwise.

**Comment by simsong** [comment]
You can look into the tests. Click on "Details"s and you'll see that the Lint with flake8 is giving an error:

image


Then click the disclosure triangle to open:

image

**Comment by simsong** [comment]
It's pedantic. But it makes us better! Do you know about py.charm? If you aren't using EMACS to edit your code, you should be using py.charm, which will pick up all of these.

**Comment by joedinsmoor** [comment]
Ok, thats what I thought. I knew to look at the error under flake8, but didn't know what was causing code 1. I'll get py.charm now

**Comment by simsong** [comment]
You may need to merge in my new code.

**Comment by simsong** [comment]
> Ok, thats what I thought. I knew to look at the error under flake8, but didn't know what was causing code 1. I'll get py.charm now

Use your student account and get the full "educational" version.

**Pull request closed without merging**
