### PR TITLE
More test cases

### PR DESCRIPTION
**Pull request by joedinsmoor**

### CODE REVIEW

**Comment by simsong** [comment]
Hi @joedinsmoor . Looks like the CI tests are failing. Can you fix the errors and push again to this branch? 
See:
https://github.com/simsong/digitalcorpora-stats/pull/13/checks?check_run_id=793229779

**Comment by simsong** [comment]
Hm. Given the error, I'm surprised that the `py.test` ran properly when you ran it.

**Comment by simsong** [comment]
You can run the CI tests locally if you wish. It's frequently faster than doing a push and waiting to see what happens.

**Comment by joedinsmoor** [comment]
Somehow, the checker isn't seeing the final ' at the end of line 5. I don't know why that is.

**Comment by joedinsmoor** [comment]
it works fine on my aws vm

**Comment by simsong** [comment]
Are you running flake8?
Here is the test that is failing:
image

**Comment by simsong** [comment]
This line does not have a final single quote:
https://github.com/simsong/digitalcorpora-stats/blob/more-test-cases/python/tests/parser_test.py#L5

**Comment by joedinsmoor** [comment]
image
this is what was changed in the last push

**Comment by simsong** [comment]
> it works fine on my aws vm

I'm not sure how it could possibly work on your aws vm. Observe:
```
(base) simsong@nimi tmp % wget https://raw.githubusercontent.com/simsong/digitalcorpora-stats/more-test-cases/python/tests/parser_test.py
--2020-06-21 17:12:45--  https://raw.githubusercontent.com/simsong/digitalcorpora-stats/more-test-cases/python/tests/parser_test.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.248.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.248.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2107 (2.1K) [text/plain]
Saving to: ‘parser_test.py’

parser_test.py                               100%[===========================================================================================>]   2.06K  --.-KB/s    in 0.001s

2020-06-21 17:12:45 (3.68 MB/s) - ‘parser_test.py’ saved [2107/2107]

(base) simsong@nimi tmp % python3 parser_test.py
  File "parser_test.py", line 5
    LINE3 = '129.174.125.204 - - [16/Jun/2019:09:06:56 -0400] "GET /corpora/scenarios/2009-m57-patents/ HTTP/1.1" 200 3812 "http://downloads.digitalcorpora.org/corpora/scenarios/2009-m57-patents/drives-redacted/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
                                                                                                                                                                                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
(base) simsong@nimi tmp %
```

Can you please post your py.test command line and output? It would be nice to debug why it works for you when it seems to contain a syntax error. Please post:
1.  `$ ls -l python python/tests`
2. `$ py.test python`

Thanks!

**Comment by simsong** [comment]
Looks like you didn't push it onto the branch associated with this pull request.

**Comment by joedinsmoor** [comment]
ah, I see.

**Comment by simsong** [comment]
Hm. Looks like it *is* there. Let me try to do a checkout. It may be that the CI test wasn't re-run automatically because you did a merge into the pull request from another branch, rather than a push to this branch.

**Comment by simsong** [comment]
Hm. Looks like it isn't there:
```
(base) simsong@nimi digitalcorpora-stats % git remote -v
origin	git@github.com:simsong/digitalcorpora-stats.git (fetch)
origin	git@github.com:simsong/digitalcorpora-stats.git (push)
(base) simsong@nimi digitalcorpora-stats % git fetch
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From github.com:simsong/digitalcorpora-stats
   1b5c1ef..6ac2d19  more-test-cases -> origin/more-test-cases
(base) simsong@nimi digitalcorpora-stats % git checkout more-test-cases
Branch 'more-test-cases' set up to track remote branch 'more-test-cases' from 'origin'.
Switched to a new branch 'more-test-cases'
(base) simsong@nimi digitalcorpora-stats % py.test
============================================================================== test session starts ==============================================================================
platform darwin -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /Users/simsong/gits/digitalcorpora-stats
plugins: hypothesis-5.5.4, arraydiff-0.3, remotedata-0.3.2, openfiles-0.4.0, doctestplus-0.5.0, astropy-header-0.1.2
collected 0 items / 2 errors

==================================================================================== ERRORS =====================================================================================
________________________________________________________________________ ERROR collecting parser_test.py ________________________________________________________________________
ImportError while importing test module '/Users/simsong/gits/digitalcorpora-stats/parser_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
parser_test.py:1: in <module>
    import weblog
E   ModuleNotFoundError: No module named 'weblog'
_________________________________________________________________ ERROR collecting python/tests/parser_test.py __________________________________________________________________
../../opt/anaconda3/lib/python3.7/site-packages/_pytest/python.py:493: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../opt/anaconda3/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:677: in _load_unlocked
    ???
../../opt/anaconda3/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:134: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
../../opt/anaconda3/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:319: in _rewrite_test
    tree = ast.parse(source, filename=fn)
../../opt/anaconda3/lib/python3.7/ast.py:35: in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
E     File "/Users/simsong/gits/digitalcorpora-stats/python/tests/parser_test.py", line 5
E       LINE3 = '129.174.125.204 - - [16/Jun/2019:09:06:56 -0400] "GET /corpora/scenarios/2009-m57-patents/ HTTP/1.1" 200 3812 "http://downloads.digitalcorpora.org/corpora/scenarios/2009-m57-patents/drives-redacted/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
E                                                                                                                                                                                                                                                                                                                                            ^
E   SyntaxError: EOL while scanning string literal
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================== 2 errors in 0.15s ===============================================================================
(base) simsong@nimi digitalcorpora-stats %
```

**Comment by simsong** [comment]
I manually added the ' in commit https://github.com/simsong/digitalcorpora-stats/commit/80a7a856d9fb2051f144ea2951eb7e81c5ebd35f

**Comment by simsong** [comment]
Now we have these three CI errors:
```

python/tests/parser_test.py:7:1: E302 expected 2 blank lines, found 1
python/tests/parser_test.py:20:1: E302 expected 2 blank lines, found 1
python/tests/parser_test.py:33:1: E302 expected 2 blank lines, found 1
##[error]Process completed with exit code 1.

```

**Comment by simsong** [comment]
blank lines added in https://github.com/simsong/digitalcorpora-stats/commit/fd87eaa017ffa0231b4c8e54fb9e9edfd7d21f32

**Comment by simsong** [comment]
Now we have this error:
```
python/tests/parser_test.py:21:1: W293 blank line contains whitespace
```

Probably my fault.

**Comment by simsong** [comment]
So if we think that W293 is too annoying, we can make it an ignored warning. But for now, I think that it's useful to require this level of quality.

**Comment by joedinsmoor** [comment]
OK. Output from those commands is as follows: 
```
jdinsmoor@instance-1:~/digitalcorpora-stats$ ls -l python python/tests
python:
total 24
-rw-r--r-- 1 jdinsmoor jdinsmoor   21 Jun 21 21:18 Makefile
-rw-r--r-- 1 jdinsmoor jdinsmoor 2108 Jun 21 21:20 parser_test.py
-rw-r--r-- 1 jdinsmoor jdinsmoor  354 Jun 21 21:18 schema.sql
drwxr-xr-x 2 jdinsmoor jdinsmoor 4096 Jun 21 21:23 tests
-rw-r--r-- 1 jdinsmoor jdinsmoor 1938 Jun 21 21:18 weblog.py
-rw-r--r-- 1 jdinsmoor jdinsmoor 2272 Jun 21 21:24 weblog.pyc

python/tests:
total 0
-rw-r--r-- 1 jdinsmoor jdinsmoor 0 Jun 21 21:18 __init__.py
jdinsmoor@instance-1:~/digitalcorpora-stats$ py.test python
============================================= test session starts ==============================================
platform linux2 -- Python 2.7.16, pytest-4.6.10, py-1.8.1, pluggy-0.13.1
rootdir: /home/jdinsmoor/digitalcorpora-stats
collected 3 items                                                                                              

python/parser_test.py ...                                                                                [100%]

=========================================== 3 passed in 0.05 seconds ===========================================
jdinsmoor@instance-1:~/digitalcorpora-stats$ 
```

**Comment by simsong** [comment]
Now I'm going to remove the cov test because I don't really understand it.

**Comment by joedinsmoor** [comment]
there we go.

**Comment by simsong** [comment]
I moved weblog.py into a module called weblog.py. Now the test can do 'import weblog from weblog' and it works no matter whether py.test is run from within the tests directory, or the python directory, or the parent directory. This is something that I still don't really understand, but it works now!

**Comment by simsong** [comment]
Thanks for your patience on this. We now have a functional CI and a functional first test. And a functional weblog parser. So I'll put together later tonight a recommended set of sequence of steps to get this project moving to the next milestone.

**Comment by joedinsmoor** [comment]
Thank you for the help.

**Comment by simsong** [comment]
Sure thing. We'll decide if we want to keep the annoying white-space checks. I'll add a 'make check' target on the Makefile to run everything so we don't need to send it to CI.

**Pull request merged**
