### PR TITLE
first prototype of webdb class added

### PR DESCRIPTION
**Pull request by joedinsmoor**
Creation and parsing of logs into mySQL database, using test credentials

### CODE REVIEW

**Comment by joedinsmoor** [comment]
> 
> 
> Good start. However:
> 
>     * Never put usernames and passwords in a git repo. They should be read from a configuration file that is explicitly _not_ in the repo.  This repo is public. You now need to change your username and password!
> 
>     * The tests should go in a file called webdb_test.py and be in the tests directory.
> 
>     * Generally, the test should be testing creating the _table_, not the database. The database should already exist. That way the test user only needs 'CREATE TABLE' privs, and not 'CREATE DATABASE' privs.
> 
> 
> Want to give another try?

Those are just placeholder credentials at the moment. 

I'll get started on the second prototype

**Comment by simsong** [comment]
Right, but don't even put in placeholder credentials. Here's what I did elsewhere:
https://github.com/summer-2020-interns/mailtools/blob/master/config.ini_demo

And here is how you would read the credentials from a config file:
https://github.com/summer-2020-interns/mailtools/blob/master/autoresponder/autoresponder.py#L70

**Comment by joedinsmoor** [comment]
got it, i'll implement a config file now

**Comment by simsong** [comment]
Right. You don't commit the config file, but you commit the config file prototype. Another way to do it is you set the username and password in your .bashrc file and read them from environment variables.

**Pull request closed without merging**
