### PR TITLE
added json building capability

### PR DESCRIPTION
**Pull request by joedinsmoor**

### CODE REVIEW

**Comment by simsong** [comment]
Hi @joedinsmoor . Did you try running the checks locally before pushing?
```
python/tests/webdb_test.py:1:1: F401 'weblog' imported but unused
15
python/tests/webdb_test.py:3:1: F401 'datetime.date' imported but unused
16
python/tests/webdb_test.py:3:1: F401 'datetime.datetime' imported but unused
17
python/tests/webdb_test.py:3:1: F401 'datetime.timedelta' imported but unused
18
python/tests/webdb_test.py:18:13: E128 continuation line under-indented for visual indent
19
python/tests/webdb_test.py:19:13: E128 continuation line under-indented for visual indent
20
python/tests/webdb_test.py:29:51: E231 missing whitespace after ':'
21
python/tests/webdb_test.py:35:1: E128 continuation line under-indented for visual indent
22
python/tests/webdb_test.py:36:1: E128 continuation line under-indented for visual indent
23
python/tests/webdb_test.py:38:5: E122 continuation line missing indentation or outdented
24
python/tests/webdb_test.py:39:5: E122 continuation line missing indentation or outdented
25
python/tests/webdb_test.py:40:5: E122 continuation line missing indentation or outdented
26
python/tests/webdb_test.py:41:1: E122 continuation line missing indentation or outdented
27
python/tests/webdb_test.py:42:1: E122 continuation line missing indentation or outdented
28
##[error]Process completed with exit code 1.
```

**Comment by joedinsmoor** [comment]
I did, but not with flake8. The only issues that are being drawn are indentation errors. Pytest comes back clean.

**Comment by joedinsmoor** [comment]
Pycharm seems to ignore the indentation errors

**Comment by joedinsmoor** [comment]
I was using Komodo, but once the indentation errors were shown here, I switched to pycharm.

**Comment by simsong** [comment]
The other issue is unnecessary imports. They do slow down the program, but I tend not to care about them so much. I should.

**Comment by simsong** [comment]
> I was using Komodo, but once the indentation errors were shown here, I switched to pycharm.

And pycharm didn't complain?

**Comment by joedinsmoor** [comment]
it did not. I ran autopep8, to automatically fix the indentation errors, and flake8 still complained.

**Comment by joedinsmoor** [comment]
indentation is now fixed, I'm going to comment out the unused imports as they will be needed later.

**Comment by joedinsmoor** [comment]
I am confused as to why pytest is erroring here and not on my vm.

**Comment by simsong** [comment]
Looks like you have the mysql connector installed on your home machine but not in the CI environment. 
I used pymysql, which I install in the unit test environment:
See: 
* https://github.com/simsong/digitalcorpora-stats/blob/master/python/tests/schema_test.py

**Comment by simsong** [comment]
If you are confused, did you look at the error? Click 'Details', then expand the error. The problem is clearly indicated in Line 25:
image

It's really important to read error messages!

**Comment by joedinsmoor** [comment]
I read the error message, it just didn't occur to me that we had a different mysql module in the CI environment.

**Comment by simsong** [comment]
Yeah. Python's support for mysql is frustrating. The advantage of pymysql is that it is pure-python.

**Comment by joedinsmoor** [comment]
Ok, I am making syntax changes to my code to conform to pymysql standards. Should be done in an hour or so.

**Comment by simsong** [comment]
Great. The changes are not severe. This is why I use the ctools.dbfile class. It can talk to both, and tries both.

**Pull request closed without merging**
